export const ADD_PRODUCT_LIST = "ADD_PRODUCT_LIST";
export const ADD_FILTER_PRODUCT_BY_BRAND = "ADD_FILTER_PRODUCT_BY_BRAND";
export const ADD_FILTER_PRODUCT_BY_CATEGORY = "ADD_FILTER_PRODUCT_BY_CATEGORY";
